### PR TITLE
fixed a few bugs affecting functionality on Linux

### PR DESCRIPTION
**Pull request by dcx86r**
Hi, I noticed some changes were made to the Linux-specific sysinfo stuff to accomodate FreeBSD. Unfortunately, the changes broken functionality on Linux!

The main issue is that the preprocessor macro was changed to `__LINUX__`, which is an invalid value. I have changed this back to `__linux__`.

With that the code compiles again but the RAM related output is off due to changes in the calculation of RAM. I'm not sure why `pow(1024,2)` was removed because according to the libsysinfo manpage the source should output the same data as on Linux. I have changed this to divide by a hardcoded value instead, so that `math.h` is no longer needed to supply `pow`.

I also noticed an issue with logo drawing in that the max height printed is the logo's height, meaning that if a logo is 6 rows in height but 8 items are configured to print, only 6 of the items will print and the
last two are cut off. This seems to be caused by lines 120-121, I'm not sure where this section is heading exactly so I just commented those lines out for now so all the data gets printed.

Finally, I cleaned up some types and specifiers to quiet some GCC warnings. I'm fairly confident this should all work on BSD as well now but don't hold me to that...

### CODE REVIEW

**Comment by trvv** [comment]
Awesome, thanks! Kind of weird because I'm running Linux and it compiled fine as long as I provided `nosysinfo=`

**Comment by dcx86r** [comment]
I actually didn't notice how it's working with the Makefile, I was testing it mainly with `tcc` so I can build it on an embedded system where GCC toolchain is too heavy, then I ran it with `gcc` just to check for warnings.

Thanks for merging my PR, I also have code ready for fetching CPU info on Linux, planning to commit that to my testing branch soon and then get a BSD VM running to see what's up there, AFAIK the BSDs have a common API for this stuff so maybe it won't take long to add support for that too

**Comment by trvv** [comment]
Awesome! Thanks for taking the time to make this project suck less.

**Comment by dcx86r** [comment]
Cheers! It's been helping refresh my C skillz :+1:

**Pull request merged**
